export const JUNK_SINGLE_ITEM_PRICE = 100;
export const JUNK_QUARTER_LOAD_PRICE = 175;

export const JUNK_VOLUME_UNIT_PRICE = JUNK_QUARTER_LOAD_PRICE;

export const JUNK_VOLUME_PRICING = {
  singleItem: JUNK_SINGLE_ITEM_PRICE,
  quarter: JUNK_VOLUME_UNIT_PRICE,
  half: JUNK_VOLUME_UNIT_PRICE * 2,
  threeQuarter: JUNK_VOLUME_UNIT_PRICE * 3,
  full: JUNK_VOLUME_UNIT_PRICE * 4
} as const;

