const base = require("./jest.config.cjs");

/**
 * Opt-in Partner Portal PostgreSQL evidence lane. These suites require a
 * disposable, fully migrated DATABASE_URL and are intentionally absent from
 * the ordinary Partner unit lane.
 */
module.exports = {
  ...base,
  globalSetup: "<rootDir>/scripts/partner-postgres-test-guard.cjs",
  testMatch: [
    "<rootDir>/src/__tests__/partner-multi-service.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-structured-rates.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-staff-owner-alerts.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-management-request-inbox.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-portal-account-readiness.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-additional-service.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-additional-service-links.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-statement-refund-scope.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-invoice-legacy-scalar.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-media-restore.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-overview.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-staff-named-resources.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-billing-history.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-template-maintenance.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-service-review-queue.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-company-directory.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-completion-record.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-billing-documents.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-billing-administration.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-approval-scope.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-relationship-invitations.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-service-record.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-invoice-ledger.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-service-reports.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-change-order-price.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-allocation-reconciliation.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/calendar-external-busy.integration.test.ts",
    "<rootDir>/src/__tests__/partner-account-cancellation-policy-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-account-lifecycle-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-approval-rule-administration-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-billing-dispute-requests-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-account-scheduling-policy-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-password-cutover-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-cancellation-request-lifecycle-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-job-change-request-lifecycle-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-location-portfolio-controls-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-location-and-account-merge-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-portal-v2-media-integrity-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-portal-operations-query-budget-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-portal-v2-scheduling-concurrency.integration.test.ts",
    "<rootDir>/src/__tests__/partner-recurring-series-lifecycle-concurrency.postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-quote-account-binding-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-quote-approval-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/partner-quote-terminal-contention-postgres.integration.test.ts",
    "<rootDir>/src/__tests__/staff-notification-operations-postgres.integration.test.ts",
  ],
};
